name: Trigger auto deployment for resto-hemat-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/resto-hemat-api-AutoDeployTrigger-c7c93b63-9e6d-4421-9777-3199a290f659.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RESTOHEMATAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: restoapi.azurecr.io
          registryUsername: ${{ secrets.RESTOHEMATAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RESTOHEMATAPI_REGISTRY_PASSWORD }}
          containerAppName: resto-hemat-api
          resourceGroup: rg-forresto
          imageToBuild: restoapi.azurecr.io/resto-hemat-api:${{ github.sha }}
          

     

